import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-[var(--color-bg-page)] text-[var(--color-text)]">
      <div className="mx-auto max-w-3xl px-5 py-12 sm:px-8 sm:py-16">
        <p className="font-ui text-[12px] uppercase tracking-[0.22em] text-[var(--color-text-muted)]">
          Disclaimer
        </p>
        <h1 className="font-display mt-5 text-[3.25rem] leading-[0.95] tracking-[-0.05em] sm:text-[4.5rem]">
          Disclaimer
        </h1>

        <div className="mt-8 space-y-5 max-w-2xl text-[16px] leading-[1.8] text-[var(--color-text-secondary)]">
          <p>
            Open-source software, provided for educational and research purposes.
          </p>
          <p>
            Information is generated by automated systems and is not guaranteed accurate, complete, or current.
          </p>
          <p>
            Not investment advice. Not business advice. Not professional advice of any kind.
          </p>
          <p>
            Verify anything important against primary sources before acting on it, and use your own judgment for any financial, hiring, product, legal, or operational decision.
          </p>
        </div>

        <div className="mt-10 flex flex-wrap gap-3">
          <Link href="/" className="button-primary">
            Back to Eigen Terminal
          </Link>
        </div>
      </div>
    </main>
  );
}
